debug: True
db_path: 'database'
log_path: 'log'
database: 'database.sqlite'

logger:

  window_logger:
    name: 'WindowLogger'
    info_log: 'window_info.log'
    error_log: 'window_error.log'
    format: '[%(asctime)s] %(levelname)s - %(message)s'

  db_logger:
    name: 'DatabaseLogger'
    info_log: 'db_info.log'
    error_log: 'db_error.log'
    format: '[%(asctime)s] %(levelname)s = %(message)s'

main_window:
  title: 'Song Database'
    
database_entities:

  category_table:
    name: 'Category'
    columns:
      id: ['CategoryID', 'INTEGER', 'PRIMARY KEY'] 
      name: ['CategoryName', 'TEXT', 'NOT NULL']
  
  song_table:
    name: 'Song'
    columns:
      id: ['SongID', 'INTEGER', 'PRIMARY KEY']
      title: ['Title', 'TEXT', 'NOT NULL']
  
  album_table:
    name: 'Album'
    columns:
      id: ['AlbumID', 'INTEGER', 'PRIMARY KEY']
      title: ['Title', 'TEXT', 'NOT NULL']
      year: ['Year', 'TEXT', 'NOT NULL']
  
  artist_table:
    name: 'Artist'
    columns:
      id: ['ArtistID', 'INTEGER', 'PRIMARY KEY']
      name: ['ArtistName', 'TEXT', 'UNIQUE']

database_relations:

  isin_table:
    name: 'IsIn'
    foreign_keys: ['CategoryID', 'SongID']
    columns:
      category_id: ['CategoryID', 'INTEGER', 'NOT NULL']
      song_id: ['SongID', 'INTEGER', 'NOT NULL']
  
  plays_table:
    name: 'Plays'
    foreign_keys: ['SongID', 'ArtistID']
    columns:
      song_id: ['SongID', 'INTEGER', 'NOT NULL']
      artist_id: ['ArtistID', 'INTEGER', 'NOT NULL']
  
  ison_table:
    name: 'IsOn'
    foregin_keys: ['SongID', 'AlbumID']
    columns:
      song_id: ['SongID', 'INTEGER', 'NOT NULL']
      album_id: ['AlbumID', 'INTEGER', 'NOT NULL']

