debug: True
db_path: 'database'
log_path: 'log'
database: 'database.sqlite'

logger:

  window_logger:
    name: 'WindowLogger'
    info_log: 'window_info.log'
    error_log: 'window_error.log'
    format: '[%(asctime)s] %(levelname)s - %(message)s'

  db_logger:
    name: 'DatabaseLogger'
    info_log: 'db_info.log'
    error_log: 'db_error.log'
    format: '[%(asctime)s] %(levelname)s = %(message)s'

main_window:
  title: 'Song Database'
    
database_tables:

  category_table:
    name: 'Category'
    type: 'entity'
    columns:
      id: ['CategoryID', 'INTEGER', 'PRIMARY KEY', 'AUTOINCREMENT'] 
      name: ['CategoryName', 'TEXT', 'NOT NULL', 'UNIQUE']
  
  song_table:
    name: 'Song'
    type: 'entity'
    columns:
      id: ['SongID', 'INTEGER', 'PRIMARY KEY', 'AUTOINCREMENT']
      title: ['Title', 'TEXT', 'NOT NULL']
  
  album_table:
    name: 'Album'
    type: 'entity'
    columns:
      id: ['AlbumID', 'INTEGER', 'PRIMARY KEY', 'AUTOINCREMENT']
      title: ['Title', 'TEXT', 'NOT NULL']
      year: ['Year', 'TEXT', 'NOT NULL']
  
  artist_table:
    name: 'Artist'
    type: 'entity'
    columns:
      id: ['ArtistID', 'INTEGER', 'PRIMARY KEY', 'AUTOINCREMENT']
      name: ['Name', 'TEXT', 'NOT NULL', 'UNIQUE']

  isin_table:
    name: 'IsIn'
    type: 'relation'
    columns:
      category_id: ['CategoryID', 'INTEGER', 'NOT NULL', 'REFERENCES Category(id)']
      song_id: ['SongID', 'INTEGER', 'NOT NULL', 'REFERENCES Song(id)']
      primary_keys: ['PRIMARY KEY (CategoryID, SongID)']
  
  plays_table:
    name: 'Plays'
    type: 'relation'
    columns:
      song_id: ['SongID', 'INTEGER', 'NOT NULL', 'REFERENCES Song(id)']
      artist_id: ['ArtistID', 'INTEGER', 'NOT NULL', 'REFERENCES Artist(id)']
      primary_keys: ['PRIMARY KEY (SongID, ArtistID)']
  
  ison_table:
    name: 'IsOn'
    type: 'relation'
    columns:
      song_id: ['SongID', 'INTEGER', 'NOT NULL', 'REFERENCES Song(id)']
      album_id: ['AlbumID', 'INTEGER', 'NOT NULL', 'REFERENCES Album(id)']
      primary_keys: ['PRIMARY KEY (SongID, AlbumID)']

