name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]
        extension:
          - bin
          - exe
          - app

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Package with PyInstaller
      run: |
        poetry run pyinstaller \
          --name songdatabase.${{ matrix.extension }} \
          --distpath /dist/${{ matrix.extension }} \
          --add-data "log:log" \
          --add-data "database:database" \
          --add-data "config.yml:."
          src/songdatabase/app.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: songdatabase-${{ matrix.os }}
        path: dist/${{ matrix.os }}
          
      
    
