name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            extension: bin
          - os: windows-latest
            extension: exe
          - os: macos-latest
            extension: app
        python-version: ["3.10"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Create Distribution Directory
      run: mkdir -p dist/${{ matrix.os }}
      working-directory: ${{ github.workspace }}

    - name: Package with PyInstaller
      run: |
        poetry run pyinstaller \
          --name songdatabase.${{ matrix.extension }} \
          --distpath dist/${{ matrix.extension }} \
          --add-data "log:log" \
          --add-data "database:database" \
          --add-data "config.yml:." \
          src/songdatabase/app.py
      working-directory: ${{ github.workspace }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: songdatabase-${{ matrix.os }}
        path: dist/${{ matrix.os }}
