name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'Add built artifacts')"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            extension: bin
          - os: windows-latest
            extension: exe
          - os: macos-latest
            extension: app
        python-version: ["3.10"]

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

  
      - name: Package with PyInstaller
        run: |
          poetry run pyinstaller \
            --name songdatabase.${{ matrix.extension }} \
            --distpath dist/${{ matrix.os }} \
            --add-data "log:log" \
            --add-data "database:database" \
            --add-data "config.yml:." \
            src/songdatabase/app.py
        working-directory: ${{ github.workspace }}
        
      - name: Commit and Push Artifacts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cp -r dist/* .
          git add .
          git commit -m "Add built artifacts for ${{ matrix.os }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
